from PyQt5.QtCore import Qt
from gas.cons.key_code import KeyCode

SPECIAL_KEY_MAP = {
    # 系统/导航键
    Qt.Key.Key_Escape: KeyCode.ESCAPE,
    Qt.Key.Key_Space: KeyCode.SPACE,
    Qt.Key.Key_Enter: KeyCode.ENTER,
    Qt.Key.Key_Return: KeyCode.ENTER,
    Qt.Key.Key_Tab: KeyCode.TAB,
    Qt.Key.Key_Backspace: KeyCode.BACK,
    Qt.Key.Key_Delete: KeyCode.DELETE,
    Qt.Key.Key_Up: KeyCode.DPAD_UP,
    Qt.Key.Key_Down: KeyCode.DPAD_DOWN,
    Qt.Key.Key_Left: KeyCode.DPAD_LEFT,
    Qt.Key.Key_Right: KeyCode.DPAD_RIGHT,
    # 游戏核心键（WASD + 常用操作）
    Qt.Key.Key_W: KeyCode.W,
    Qt.Key.Key_A: KeyCode.A,
    Qt.Key.Key_S: KeyCode.S,
    Qt.Key.Key_D: KeyCode.D,
    Qt.Key.Key_Q: KeyCode.Q,
    Qt.Key.Key_E: KeyCode.E,
    Qt.Key.Key_R: KeyCode.R,
    Qt.Key.Key_F: KeyCode.F,
    Qt.Key.Key_C: KeyCode.C,
    Qt.Key.Key_V: KeyCode.V,
    Qt.Key.Key_X: KeyCode.X,
    Qt.Key.Key_Z: KeyCode.Z,
    # 修饰键
    Qt.Key.Key_Shift: KeyCode.LSHIFT,
    Qt.Key.Key_Control: KeyCode.CONTROL,
    Qt.Key.Key_Alt: KeyCode.ALT,
    Qt.Key.Key_CapsLock: KeyCode.CAPS_LOCK,
    # F1 ~ F12
    Qt.Key.Key_F1: KeyCode.F1,
    Qt.Key.Key_F2: KeyCode.F2,
    Qt.Key.Key_F3: KeyCode.F3,
    Qt.Key.Key_F4: KeyCode.F4,
    Qt.Key.Key_F5: KeyCode.F5,
    Qt.Key.Key_F6: KeyCode.F6,
    Qt.Key.Key_F7: KeyCode.F7,
    Qt.Key.Key_F8: KeyCode.F8,
    Qt.Key.Key_F9: KeyCode.F9,
    Qt.Key.Key_F10: KeyCode.F10,
    Qt.Key.Key_F11: KeyCode.F11,
    Qt.Key.Key_F12: KeyCode.F12,
    # 主键盘区数字 0~9（切换武器、技能等）
    Qt.Key.Key_0: KeyCode.DIGIT_0,
    Qt.Key.Key_1: KeyCode.DIGIT_1,
    Qt.Key.Key_2: KeyCode.DIGIT_2,
    Qt.Key.Key_3: KeyCode.DIGIT_3,
    Qt.Key.Key_4: KeyCode.DIGIT_4,
    Qt.Key.Key_5: KeyCode.DIGIT_5,
    Qt.Key.Key_6: KeyCode.DIGIT_6,
    Qt.Key.Key_7: KeyCode.DIGIT_7,
    Qt.Key.Key_8: KeyCode.DIGIT_8,
    Qt.Key.Key_9: KeyCode.DIGIT_9,
}
